name: CI with Gradle

on:
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest


    services:
      redis:
        image: redis:latest
        ports:
          - "6379:6379"
      steps:
        - uses: actions/checkout@v3

    steps:
      - uses: actions/checkout@v3
      # Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: api:build -x test

      # 빌드
      - name: test CI
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test

      # 테스트 결과 PR 코멘트에 등록
      - name: Register the test results as PR comments
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/api/build/test-results/test/TEST-*.xml
            **/core/build/test-results/test/TEST-*.xml


      # 테스트 실패시 코드 라인에 대한 체크 추가
      - name: If test fail, add check comment on failed code line
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: |
            **/api/build/test-results/test/TEST-*.xml
            **/core/build/test-results/test/TEST-*.xml

